repos:
  - repo: local
    hooks:
      - id: commitizen-check
        name: Commitizen Check
        entry: cz check --rev-range origin/master..
        language: system
        pass_filenames: false