repos:
  - repo: local
    hooks:
      - id: commitizen-check
        name: Commitizen Check
        entry: cz check --commit-msg-file $1
        language: system
        stages: [commit-msg]
        pass_filenames: false