# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: # Added strategy matrix
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} # Use matrix variable
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }} # Use matrix variable

    - name: Verify Python Version # Added verification step
      run: |
        INSTALLED_VERSION=$(python --version)
        echo "Using Python version: $INSTALLED_VERSION"
        if [[ "$INSTALLED_VERSION" != *"${{ matrix.python-version }}"* ]]; then
          echo "Error: Python version mismatch! Expected ${{ matrix.python-version }}, got $INSTALLED_VERSION"
          exit 1
        fi
      shell: bash

    - name: Install uv # Combined uv install and PATH steps
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    # Removed activate uv step, uv sync/run handle environment

    - name: Install dependencies # Use uv sync
      run: uv sync --all-extras
      shell: bash

    - name: Check kek version # Use dynamic version from __init__.py
      run: |
        KEK_VERSION_OUTPUT=$(uv run kek version)
        echo "Reported version output: $KEK_VERSION_OUTPUT"
        # Extract version from __init__.py using Python
        EXPECTED_VERSION_NUM=$(python -c 'import re; print(re.search(r"^__version__\s*=\s*[\"'\'']([^\"'\'']+)[\"'\'']", open("src/kek/__init__.py").read(), re.MULTILINE).group(1))')
        EXPECTED_OUTPUT="kek version $EXPECTED_VERSION_NUM"
        echo "Expected version output: $EXPECTED_OUTPUT"
        if [ "$KEK_VERSION_OUTPUT" != "$EXPECTED_OUTPUT" ]; then
          echo "Error: Version mismatch! Expected '$EXPECTED_OUTPUT', got '$KEK_VERSION_OUTPUT'"
          exit 1
        fi
      shell: bash

    - name: Lint with Ruff
      run: uv run ruff check .
      shell: bash

    - name: Run tests with Pytest
      run: uv run pytest -v
      shell: bash 