name: Release

on:
  push:
    branches: [master]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and semantic-release
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install python-semantic-release build

      - name: Run Semantic Release
        run: semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
