name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv and semantic-release
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
  

      - name: Release to PyPI & GitHub
        uses: python-semantic-release/python-semantic-release@v9
        with:
          build-command: uv pip install build && uv python -m build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}